version: "3"
services:
  dev:
    build: "."
    ports:
      - 8890:8888
    volumes:
      - ./work:/work
    working_dir: /work
    entrypoint: jupyter lab --no-browser --allow-root --ip 0.0.0.0 --port 8890
