version: "3.9"
services:
  dev:
    build:
      context: "."
      dockerfile: Dockerfile-R
    image: c2dhunilu/journal-of-digital-history-jupyter-r:latest
    ports:
      - 8890:8888
    volumes:
      - ./work:/work
    working_dir: /work
    entrypoint: jupyter lab --no-browser --allow-root --ip 0.0.0.0 --port 8890
