"""
Rewrite the citations in work/shelters-for-all.ipynb to JDH official format.

JDH official inline format (Chicago Author-Date):
    (<cite data-cite="LIBRARY_ID/ITEM_KEY"></cite>)
    (<cite data-cite="LIB/K1"></cite>; <cite data-cite="LIB/K2"></cite>)
    (<cite data-cite="LIB/K"></cite>, 22)
    As shown by <cite data-cite="LIB/K"></cite>

The visible "(Author Year)" text is rendered by the JDH Jupyter viewer
(jupyterlab-citation-manager) at view time from data-cite alone.

Bibliography is generated by Better BibTeX's item.bibliography JSON-RPC with
the chicago-author-date CSL style and contentType=html, then wrapped with
<i id="zotero|GROUP/KEY"></i> anchors at the start of each csl-entry.

Library: MELICA, web group ID 5390891, local id 7.
"""

import json
import re
import sys
import unicodedata
from pathlib import Path
from urllib.request import Request, urlopen

REPO = Path(__file__).parent
BIB = REPO / "JDH-spatial-equity.bib"
NB = REPO / "work" / "shelters-for-all.ipynb"
NB_BAK = REPO / "work" / "shelters-for-all.ipynb.bak"
GROUP_ID = 5390891  # MELICA web group id (used in data-cite and anchors)
LIBRARY_ID = 7  # local BBT library id for MELICA
ZOT_API = "http://localhost:23119/api"
BBT_RPC = "http://localhost:23119/better-bibtex/json-rpc"

# User-dictated overrides keyed by (old_key_extracted_from_href, label_first_30_chars).
# Resolution: one of
#   {"action": "single", "melica_citekey": "<bbt-cite-key>"}
#   {"action": "split",  "melica_citekeys": ["ck1", "ck2"]}
#   {"action": "drop"}  — drop entire cite (used for the second of two collapsed cites)
MANUAL_OVERRIDES = {
    ("EUNFC4HT", "(Bjørnsson et al., 2020)"): {"action": "single", "melica_citekey": "bjornssonHvisKrigenKommer2020"},
    ("ZDW5BRHJ", "(Bjørnsson, 2020)"): {"action": "single", "melica_citekey": "bjornssonStandsTillobTil2020"},
    ("P7JZZXNL", "(Schultz, 1950, 10)"): {"action": "single", "melica_citekey": "beredskabsstyrelsen1950"},
    ("DS3A7BAH", "(Erhvervsstyrelsen, n.d.-a)"): {"action": "single", "melica_citekey": "bbr"},
    ("FRCF6BPE", "(Erhvervsstyrelsen, n.d.-b)"): {"action": "drop"},  # collapsed into prior
    ("ZN3ZS6A7", "(Aarhus Universitet, 2024)"): {"action": "split", "melica_citekeys": ["pedersen_arbejderkvarterer", "juhl2010"]},
    ("FH7UP7VQ", "(Referat C.F.-kommissionens møde,1956)"): {"action": "single", "melica_citekey": "ReferartAfCFkommissionens1956"},
}


def http_get_json(url):
    req = Request(url, headers={"Zotero-API-Version": "3"})
    with urlopen(req, timeout=30) as r:
        return json.loads(r.read().decode("utf-8"))


def rpc(method, params, timeout=300):
    body = json.dumps({"jsonrpc": "2.0", "method": method, "params": params, "id": 1}).encode()
    req = Request(BBT_RPC, data=body, headers={"Content-Type": "application/json"})
    with urlopen(req, timeout=timeout) as r:
        resp = json.loads(r.read().decode("utf-8"))
    if "error" in resp:
        raise RuntimeError(f"BBT error: {resp['error']}")
    if "result" not in resp:
        raise RuntimeError(f"BBT response missing 'result': {resp}")
    return resp["result"]


def norm_title(s):
    if not s:
        return ""
    s = unicodedata.normalize("NFKD", s).encode("ascii", "ignore").decode().lower()
    return re.sub(r"[^a-z0-9]+", "", s)


def fetch_melica_items():
    """Pull every item in MELICA via the local Zotero API, with item keys."""
    items = []
    start = 0
    while True:
        url = f"{ZOT_API}/groups/{GROUP_ID}/items?limit=100&start={start}&itemType=-attachment%20%7C%7C%20note"
        chunk = http_get_json(url)
        if not chunk:
            break
        items.extend(chunk)
        if len(chunk) < 100:
            break
        start += 100
    return items


def parse_bib_entries(path):
    """Tolerant @entry{key, field = value/braces,...} parser. Returns list of dicts."""
    text = path.read_text(encoding="utf-8")
    entries = []
    i = 0
    while True:
        m = re.search(r"@(\w+)\s*\{\s*([^,\s]+)\s*,", text[i:])
        if not m:
            break
        entry_start = i + m.start()
        entry_type = m.group(1).lower()
        citekey = m.group(2)
        body_start = i + m.end()
        # walk braces to find the matching closing }
        depth = 1
        j = body_start
        while j < len(text) and depth > 0:
            c = text[j]
            if c == "{":
                depth += 1
            elif c == "}":
                depth -= 1
            j += 1
        body = text[body_start : j - 1]
        i = j

        entry = {"_type": entry_type, "_citekey": citekey}
        # field parser: name = {value} OR name = "value" OR name = bareword
        k = 0
        while k < len(body):
            fm = re.match(r"\s*(\w+)\s*=\s*", body[k:])
            if not fm:
                break
            fname = fm.group(1).lower()
            k += fm.end()
            if k >= len(body):
                break
            if body[k] == "{":
                depth = 1
                k += 1
                start = k
                while k < len(body) and depth > 0:
                    if body[k] == "{":
                        depth += 1
                    elif body[k] == "}":
                        depth -= 1
                    k += 1
                val = body[start : k - 1]
            elif body[k] == '"':
                k += 1
                start = k
                while k < len(body) and body[k] != '"':
                    k += 1
                val = body[start:k]
                k += 1
            else:
                m2 = re.match(r"([^,\s]+)", body[k:])
                val = m2.group(1) if m2 else ""
                k += len(val)
            entry[fname] = re.sub(r"[{}]", "", val).strip()
            sep = re.match(r"\s*,\s*", body[k:])
            if sep:
                k += sep.end()
            else:
                break
        entries.append(entry)
    return entries


def first_surname_from_authors(authors_list):
    """authors_list is from Zotero data.creators or CSL author list; return first surname normalized."""
    if not authors_list:
        return ""
    first = authors_list[0]
    family = first.get("family") or first.get("lastName") or first.get("name") or ""
    return norm_title(family)


def index_melica(items, melica_csl):
    """Build {DOI: key}, {norm_title: [keys]}, {(surname, year): [keys]} indexes.

    items: list from Zotero local API (has 'key' and 'data' with creators)
    melica_csl: list from BBT library.json (CSL-JSON with 'citation-key', no item key)

    We merge them via DOI / title to associate citation-key with item-key.
    """
    by_doi = {}
    by_title = {}
    by_surname_year = {}
    full = {}
    for it in items:
        data = it.get("data", {})
        key = data.get("key") or it.get("key")
        if not key:
            continue
        item_type = data.get("itemType", "")
        if item_type in ("attachment", "note"):
            continue
        full[key] = data
        doi = (data.get("DOI") or "").lower().strip()
        if doi:
            by_doi.setdefault(doi, []).append(key)
        title = data.get("title", "")
        nt = norm_title(title)
        if nt:
            by_title.setdefault(nt, []).append(key)
        # creators
        authors = [c for c in data.get("creators", []) if c.get("creatorType") in (None, "author", "editor", "contributor")]
        surname = first_surname_from_authors(authors)
        date = data.get("date") or ""
        ym = re.search(r"(\d{4})", date)
        year = ym.group(1) if ym else None
        if surname and year:
            by_surname_year.setdefault((surname, year), []).append(key)
    # Merge MELICA cite-keys (from CSL dump) onto item-keys by DOI/title
    citekey_to_itemkey = {}
    for it in melica_csl:
        ck = it.get("citation-key")
        if not ck:
            continue
        doi = (it.get("DOI") or "").lower().strip()
        nt = norm_title(it.get("title", ""))
        ik = None
        if doi and doi in by_doi:
            ik = by_doi[doi][0]
        elif nt and nt in by_title:
            ik = by_title[nt][0]
        if ik:
            citekey_to_itemkey[ck] = ik
    return {
        "by_doi": by_doi,
        "by_title": by_title,
        "by_surname_year": by_surname_year,
        "full": full,
        "citekey_to_itemkey": citekey_to_itemkey,
    }


def main():
    # 1. MELICA dump via local Zotero API
    print("[1/6] Fetching MELICA items via local Zotero API...", flush=True)
    melica = fetch_melica_items()
    print(f"      retrieved {len(melica)} MELICA items (non-attachment, non-note)")

    # 2. Pull MELICA citation-keys via library.json
    print("[2/6] Fetching MELICA cite-keys via library.json...", flush=True)
    melica_cslj_path = REPO / ".melica_se.json"
    if not melica_cslj_path.exists():
        from urllib.request import urlretrieve
        urlretrieve(f"http://localhost:23119/better-bibtex/library?/{LIBRARY_ID}/library.json", str(melica_cslj_path))
    melica_csl = json.loads(melica_cslj_path.read_text(encoding="utf-8"))
    idx = index_melica(melica, melica_csl)
    print(f"      indexed {len(idx['by_doi'])} DOIs, {len(idx['by_title'])} titles, "
          f"{len(idx['by_surname_year'])} (surname,year) buckets")
    print(f"      cite-key -> item-key: {len(idx['citekey_to_itemkey'])} mapped")

    # 3. Parse .bib (for cross-reference only; .bib may be incomplete vs MELICA)
    print(f"[3/6] Parsing {BIB.name}...", flush=True)
    bib = parse_bib_entries(BIB)
    print(f"      parsed {len(bib)} entries")
    bib_to_melica = {}
    unmatched_bib = []
    for entry in bib:
        ck = entry["_citekey"]
        if ck in idx["citekey_to_itemkey"]:
            bib_to_melica[ck] = idx["citekey_to_itemkey"][ck]
            continue
        doi = (entry.get("doi") or "").lower().strip()
        if doi and doi in idx["by_doi"]:
            bib_to_melica[ck] = idx["by_doi"][doi][0]
            continue
        nt = norm_title(entry.get("title", ""))
        if nt and nt in idx["by_title"]:
            bib_to_melica[ck] = idx["by_title"][nt][0]
            continue
        unmatched_bib.append(ck)
    print(f"      .bib -> MELICA: {len(bib_to_melica)}/{len(bib)}")

    # 4. Extract inline cite tags from notebook
    print(f"[4/6] Extracting inline cites from {NB.name}...", flush=True)
    nb = json.loads(NB.read_text(encoding="utf-8"))
    cite_re = re.compile(
        r'<cite[^>]*id="([^"]*)"[^>]*>\s*<a[^>]*href="([^"]*)"[^>]*>([^<]*)</a>\s*</cite>',
        re.DOTALL,
    )
    inline_cites = []
    for ci, cell in enumerate(nb["cells"]):
        if cell["cell_type"] != "markdown":
            continue
        src = "".join(cell["source"])
        for m in cite_re.finditer(src):
            inline_cites.append((ci, m.group(0), m.group(1), m.group(2), m.group(3)))
    print(f"      found {len(inline_cites)} inline cite tags")

    def extract_old_key(href):
        gm = re.match(r"#zotero%7C(\d+)", href)
        if not gm:
            return (None, None)
        grp = gm.group(1)
        # After the group digits, well-formed: "%2F<KEY8>"
        # Broken shapes: "%2<KEY7>" (F eaten by F-prefix), "%<KEY8>" (whole %2F lost)
        tail = href[gm.end():]
        tail = re.sub(r"^%2F", "", tail)   # full separator
        tail = re.sub(r"^%2", "", tail)    # half-eaten F
        tail = re.sub(r"^%", "", tail)     # whole-separator lost
        key = re.match(r"[A-Z0-9]{6,8}", tail)
        return (grp, key.group(0)) if key else (grp, None)

    # Parse the existing bibliography cell to harvest old-key -> title map
    bib_cell_src = "".join(nb["cells"][87]["source"])
    bib_anchor_re = re.compile(
        r'<i id="zotero\|(\d+)/([A-Z0-9]+)"></i>([^<]+(?:<[^/][^>]*>[^<]*</[^>]+>[^<]*)*)',
        re.DOTALL,
    )
    old_key_to_title = {}
    for m in re.finditer(r'<div class="csl-entry">(.*?)</div>', bib_cell_src, re.DOTALL):
        chunk = m.group(1)
        am = re.match(r'\s*<i id="zotero\|(\d+)/([A-Z0-9]+)"></i>\s*(.*)', chunk, re.DOTALL)
        if am:
            grp, kk, rest = am.group(1), am.group(2), am.group(3)
            # rest looks like "Author, A. (Year). Title. <i>Journal</i>..."
            # Heuristic: title is the text between ". " after "(Year)." and the next ". <i>" or ". <"
            # Simpler: strip tags, then split on ". " and take piece after Year.
            plain = re.sub(r"<[^>]+>", "", rest)
            plain = re.sub(r"&#38;", "&", plain)
            plain = re.sub(r"&amp;", "&", plain)
            old_key_to_title[(grp, kk)] = plain.strip()

    print(f"      harvested {len(old_key_to_title)} (group, old_key) -> entry texts from bibliography cell")

    # Parse cite labels
    label_re = re.compile(
        r"\(\s*([^,()]+?)(?:\s+et\s+al\.|\s+and\s+([^,]+)|\s*&\s*([^,]+))?\s*,?\s+"
        r"(forthcoming|n\.d\.(?:[-a-z]*)|[12][0-9]{3}[a-z]?)"
        r"(?:[:,]\s*(\S[^)]*))?\s*\)"
    )

    def parse_label(label):
        m = label_re.match(label.strip())
        if not m:
            return None
        a1 = m.group(1).strip()
        a2 = (m.group(2) or m.group(3) or "").strip()  # second author surname if "X and Y" or "X & Y"
        year = m.group(4)
        page = m.group(5)
        has_etal = "et al" in label.lower()
        return {"surname": a1, "second_surname": a2, "year": year, "page": page, "etal": has_etal}

    def cands_by_surname_year(surname_raw, year_digits):
        """Get list of MELICA candidate keys for a given surname + year."""
        if not year_digits:
            return []
        surname_candidates = [norm_title(surname_raw)]
        parts = surname_raw.split()
        if parts:
            surname_candidates += [norm_title(parts[-1]), norm_title(parts[0])]
        seen = set()
        out = []
        for s in surname_candidates:
            if not s:
                continue
            if (s, year_digits) in idx["by_surname_year"]:
                for k in idx["by_surname_year"][(s, year_digits)]:
                    if k not in seen:
                        out.append(k); seen.add(k)
            if not out and len(s) >= 4:
                for (snm, yr), keys in idx["by_surname_year"].items():
                    if yr == year_digits and (s in snm or snm in s):
                        for k in keys:
                            if k not in seen:
                                out.append(k); seen.add(k)
            if out:
                break
        return out

    def filter_by_second_author(cands, second_surname):
        """Keep MELICA items whose author list includes second_surname."""
        if not second_surname:
            return cands
        s2 = norm_title(second_surname.split()[-1]) if second_surname.split() else norm_title(second_surname)
        if not s2:
            return cands
        out = []
        for k in cands:
            creators = idx["full"].get(k, {}).get("creators", [])
            for c in creators[1:]:  # skip first author
                fam = norm_title(c.get("lastName") or c.get("name") or "")
                if fam and (s2 in fam or fam in s2):
                    out.append(k)
                    break
        return out if out else cands

    def filter_solo_author(cands, has_etal, has_second):
        """If label has neither 'et al.' nor 'X and Y', prefer items with exactly one author."""
        if has_etal or has_second:
            return cands
        out = [k for k in cands if len(idx["full"].get(k, {}).get("creators", [])) == 1]
        return out if out else cands

    def collapse_duplicates(cands):
        """When multiple MELICA items have identical normalized title, treat them as equivalent
        and keep just the first (lexicographically smallest key for stability)."""
        seen_titles = {}
        for k in cands:
            t = norm_title(idx["full"].get(k, {}).get("title", ""))
            if t not in seen_titles:
                seen_titles[t] = k
        return list(seen_titles.values())

    # 5. Resolve each inline cite -> MELICA item key, page
    print("[5/6] Resolving inline cites against MELICA...", flush=True)
    resolution = []
    ambiguous_groups = {}  # (surname,year_base) -> list of resolution indices needing letter pick

    for ix, (ci, full, cid, href, label) in enumerate(inline_cites):
        grp, old_key = extract_old_key(href)
        parsed = parse_label(label)
        page = parsed["page"] if parsed else None
        melica_key = None
        melica_split_keys = None  # set for split action
        action = "single"
        status = ""

        # Tier 0: explicit manual override
        override_key = (old_key, label.strip())
        ovr = MANUAL_OVERRIDES.get(override_key)
        if ovr:
            action = ovr["action"]
            if action == "single":
                ck = ovr["melica_citekey"]
                melica_key = idx["citekey_to_itemkey"].get(ck)
                status = f"tier0:override:single->{ck}"
            elif action == "split":
                melica_split_keys = [idx["citekey_to_itemkey"].get(ck) for ck in ovr["melica_citekeys"]]
                melica_key = melica_split_keys[0] if melica_split_keys[0] else None
                status = f"tier0:override:split->{ovr['melica_citekeys']}"
            elif action == "drop":
                melica_key = "__DROP__"
                status = "tier0:override:drop"

        # Tier 1: title from bibliography cell 87
        if not melica_key and (grp, old_key) in old_key_to_title:
            title_text = old_key_to_title[(grp, old_key)]
            tm = re.search(r"\(\d{4}[a-z]?\)\.\s+([^.]+?)\.", title_text)
            if tm:
                nt = norm_title(tm.group(1))
                if nt in idx["by_title"]:
                    melica_key = idx["by_title"][nt][0]
                    status = "tier1:title-from-bib-cell-exact"
                else:
                    cand = [v for k, v in idx["by_title"].items()
                            if len(nt) > 20 and nt[:30] in k]
                    if cand and len(cand) == 1:
                        melica_key = cand[0][0]
                        status = "tier1:title-from-bib-cell-substring"

        # Tier 2: (surname, year) against MELICA
        if not melica_key and parsed:
            surname_raw = parsed["surname"].strip()
            year = parsed["year"]
            ymd = re.match(r"(\d{4})", year or "")
            yd = ymd.group(1) if ymd else None

            cands_keys = cands_by_surname_year(surname_raw, yd)
            cands_keys = filter_by_second_author(cands_keys, parsed.get("second_surname", ""))
            cands_keys = filter_solo_author(cands_keys, parsed["etal"], bool(parsed.get("second_surname")))
            cands_keys = collapse_duplicates(cands_keys)

            if len(cands_keys) == 1:
                melica_key = cands_keys[0]
                status = "tier2:surname-year+filters"
            elif len(cands_keys) > 1:
                suffix = year[4:] if year and len(year) > 4 else ""
                if suffix and "a" <= suffix <= "z":
                    cands_sorted = sorted(
                        cands_keys,
                        key=lambda k: norm_title(idx["full"].get(k, {}).get("title", "")),
                    )
                    li = ord(suffix) - ord("a")
                    if li < len(cands_sorted):
                        melica_key = cands_sorted[li]
                        status = f"tier2b:disambig-letter[{suffix}->idx{li}]"
                    else:
                        status = f"tier2:ambig-letter-out-of-range[{suffix},{len(cands_sorted)}]"
                else:
                    status = f"tier2:ambig({len(cands_keys)}-no-suffix)"

        # Tier 3: surname match against ALL authors (catches "forthcoming"/n.d./irregular years)
        if not melica_key and parsed:
            surname_raw = parsed["surname"].strip()
            second = parsed.get("second_surname", "")
            s_norms = [norm_title(p) for p in surname_raw.split()] + (
                [norm_title(p) for p in second.split()] if second else []
            )
            s_norms = [s for s in s_norms if s and len(s) >= 4]
            if s_norms:
                hits = []
                for k, data in idx["full"].items():
                    creators = data.get("creators", [])
                    cr_norms = [norm_title(c.get("lastName") or c.get("name") or "") for c in creators]
                    cr_norms = [c for c in cr_norms if c]
                    matched = sum(1 for s in s_norms if any(s in c or c in s for c in cr_norms))
                    if matched >= len(s_norms) and matched > 0:
                        hits.append(k)
                hits = collapse_duplicates(hits)
                if len(hits) == 1:
                    melica_key = hits[0]
                    status = "tier3:author-list-match"

        # Tier 4: long-title institutional/archival
        if not melica_key:
            label_words = [w for w in re.findall(r"[A-Za-zæøåÆØÅéè]{5,}", label)
                           if w.lower() not in {"forthcoming", "n.d", "nd", "kommissionens"}]
            if label_words:
                best_hits = []
                for k, data in idx["full"].items():
                    t = data.get("title", "")
                    nt_full = norm_title(t)
                    matches = sum(1 for w in label_words if norm_title(w) and norm_title(w) in nt_full)
                    if matches >= 2:
                        best_hits.append((matches, k))
                best_hits.sort(reverse=True)
                if best_hits and best_hits[0][0] >= 3:
                    melica_key = best_hits[0][1]
                    status = f"tier4:title-keyword-match({best_hits[0][0]}/{len(label_words)})"
                elif best_hits and best_hits[0][0] == 2 and len(best_hits) == 1:
                    melica_key = best_hits[0][1]
                    status = "tier4:title-keyword-unique-pair"

        if not melica_key and not status:
            status = "UNRESOLVED:no-tier-fired"

        resolution.append({
            "ix": ix, "cell": ci, "label": label, "old_html": full, "old_href": href,
            "old_grp": grp, "old_key": old_key,
            "melica_itemkey": melica_key,
            "action": action,
            "split_keys": melica_split_keys,
            "page": page, "status": status,
        })

    # Stats
    def is_resolved(r):
        if r["action"] == "drop":
            return True
        if r["action"] == "split" and r.get("split_keys") and all(r["split_keys"]):
            return True
        return bool(r["melica_itemkey"]) and r["melica_itemkey"] != "__DROP__" or r["melica_itemkey"] == "__DROP__"
    resolved = sum(1 for r in resolution if is_resolved(r))
    print(f"      resolved: {resolved}/{len(resolution)} inline cites")
    still_unresolved = [r for r in resolution if not is_resolved(r)]
    if still_unresolved:
        # Group by (old_key, label) so the user makes one decision per unique source
        from collections import defaultdict
        groups = defaultdict(list)
        for r in still_unresolved:
            groups[(r["old_key"], r["label"].strip())].append(r["cell"])
        print(f"      UNRESOLVED -- {len(still_unresolved)} occurrences, "
              f"{len(groups)} unique (old_key, label) pairs:")
        manual_map = {}
        for (ok, lab), cells in groups.items():
            print(f"\n        old_key={ok}  label={lab!r}  cells={cells}")
            # For each, compute candidate MELICA items by surname+year and print
            parsed = parse_label(lab)
            cands = []
            if parsed:
                surname_raw = parsed["surname"].strip()
                surname_candidates = [
                    norm_title(surname_raw),
                    norm_title(surname_raw.split()[-1]) if surname_raw.split() else "",
                    norm_title(surname_raw.split()[0]) if surname_raw.split() else "",
                ]
                year = parsed["year"] or ""
                ym = re.match(r"(\d{4})", year)
                yd = ym.group(1) if ym else None
                seen = set()
                for s in surname_candidates:
                    if not s:
                        continue
                    if yd and (s, yd) in idx["by_surname_year"]:
                        for k in idx["by_surname_year"][(s, yd)]:
                            if k not in seen:
                                cands.append(k); seen.add(k)
                    if not cands and yd and len(s) >= 4:
                        for (snm, yr), keys in idx["by_surname_year"].items():
                            if yr == yd and (s in snm or snm in s):
                                for k in keys:
                                    if k not in seen:
                                        cands.append(k); seen.add(k)
            # Also search MELICA item types - for institutional, try author name match anywhere
            if not cands:
                surname_text = (parsed["surname"].split()[0] if parsed else lab[1:6]).lower()
                for k, data in idx["full"].items():
                    creators = data.get("creators", [])
                    for c in creators:
                        name_field = (c.get("name") or c.get("lastName") or "").lower()
                        if name_field and surname_text in name_field:
                            cands.append(k)
                            break
                    if k in cands:
                        continue
                # Try matching by title keyword (for long institutional titles)
                if not cands:
                    long_words = [w for w in re.findall(r"[A-Za-z]{6,}", lab) if w not in ("forthcoming",)]
                    for w in long_words[:2]:
                        for k, data in idx["full"].items():
                            t = data.get("title", "").lower()
                            if w.lower() in t:
                                cands.append(k)
                                if len(cands) > 8:
                                    break
                        if cands:
                            break
            for k in cands[:8]:
                d = idx["full"].get(k, {})
                creators = d.get("creators", [])
                au = creators[0] if creators else {}
                au_str = au.get("name") or f"{au.get('lastName','?')}, {au.get('firstName','')[:1]}."
                title = d.get("title", "?")
                date = d.get("date", "?")
                print(f"          [ ] {k} | {au_str} ({date}) | {title[:70]}")
            if not cands:
                print(f"          (no MELICA candidates found by surname/title — likely not in MELICA)")
            manual_map[f"{ok}::{lab}"] = {"cells": cells, "candidates": cands[:8],
                                           "candidate_meta": [
                                               {"key": k,
                                                "title": idx["full"].get(k, {}).get("title", ""),
                                                "date": idx["full"].get(k, {}).get("date", "")}
                                               for k in cands[:8]
                                           ]}
        (REPO / ".jdh_manual_resolution.json").write_text(
            json.dumps(manual_map, indent=2, ensure_ascii=False), encoding="utf-8"
        )
        print(f"\n      Manual resolution candidates written to .jdh_manual_resolution.json")

    # Save state with safe keys
    bib_lookup = {ck: {"title": next(b for b in bib if b["_citekey"] == ck).get("title", ""),
                       "author": next(b for b in bib if b["_citekey"] == ck).get("author", "")[:60]}
                  for ck in bib_to_melica}
    state = {
        "melica_count": len(melica),
        "bib_count": len(bib),
        "bib_to_melica": bib_to_melica,
        "unmatched_bib": unmatched_bib,
        "inline_cite_count": len(inline_cites),
        "resolved_count": resolved,
        "resolution": resolution,
        "old_key_to_title_count": len(old_key_to_title),
    }
    (REPO / ".jdh_state.json").write_text(
        json.dumps(state, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    print()
    print("=== SUMMARY (resolution phase) ===")
    print(f"MELICA items: {len(melica)}")
    print(f".bib entries: {len(bib)}, in MELICA: {len(bib_to_melica)}")
    print(f"inline cite tags: {len(inline_cites)}")
    print(f"resolved inline cites: {resolved}/{len(inline_cites)} ({len(still_unresolved)} unresolved)")

    if still_unresolved:
        print("\nStopping: cannot rewrite notebook until every cite is resolved.")
        return

    # ---------------- REWRITE PHASE ----------------
    print("\n[6/8] Rewriting inline cites in notebook cells...", flush=True)

    def build_data_cite(itemkey):
        return f'<cite data-cite="{GROUP_ID}/{itemkey}"></cite>'

    def rewrite_one(r):
        """Produce the replacement HTML for one cite, given its resolution row."""
        if r["action"] == "drop":
            return ""  # full removal; caller cleans up surrounding `; `
        page = r.get("page")
        page_suffix = f", {page}" if page else ""
        if r["action"] == "split" and r["split_keys"]:
            parts = [build_data_cite(k) for k in r["split_keys"] if k]
            return "; ".join(parts) + page_suffix
        return build_data_cite(r["melica_itemkey"]) + page_suffix

    # Group resolutions by cell, then apply textual replacement in-place.
    by_cell = {}
    for r in resolution:
        by_cell.setdefault(r["cell"], []).append(r)

    total_repls = 0
    for ci, rows in by_cell.items():
        src = "".join(nb["cells"][ci]["source"])
        # Sort rows by appearance order — use the old_html string to find positions.
        # Since old_html may be unique per occurrence, we can replace each one.
        # But multiple identical old_html strings may exist; iterate find+replace one-by-one.
        for r in rows:
            old = r["old_html"]
            new = rewrite_one(r)
            # Replace just the first occurrence
            idx_pos = src.find(old)
            if idx_pos == -1:
                print(f"  WARN: could not find old_html in cell {ci}")
                continue
            src = src[:idx_pos] + new + src[idx_pos + len(old):]
            total_repls += 1
        # Clean up artifacts from drops: orphan "; " adjacent to "(" or ")" or ";"
        src = re.sub(r"\(\s*;\s*", "(", src)
        src = re.sub(r";\s*\)", ")", src)
        src = re.sub(r";\s*;\s*", "; ", src)
        # Also collapse "(<cite ...></cite>);( <cite ...></cite>)" patterns — i.e. when two
        # parenthesized blocks are adjacent we don't merge; leave as-is.
        nb["cells"][ci]["source"] = [src]

    print(f"      applied {total_repls} cite replacements across {len(by_cell)} cells")

    # ---------------- BIBLIOGRAPHY PHASE ----------------
    print("\n[7/8] Generating Chicago Author-Date bibliography via BBT...", flush=True)
    # Collect unique MELICA item keys from resolutions (excluding drops)
    cited_itemkeys = []
    seen = set()
    for r in resolution:
        if r["action"] == "drop":
            continue
        if r["action"] == "split" and r["split_keys"]:
            for k in r["split_keys"]:
                if k and k not in seen:
                    cited_itemkeys.append(k); seen.add(k)
        elif r["melica_itemkey"] and r["melica_itemkey"] != "__DROP__":
            if r["melica_itemkey"] not in seen:
                cited_itemkeys.append(r["melica_itemkey"]); seen.add(r["melica_itemkey"])
    print(f"      {len(cited_itemkeys)} unique items in bibliography")

    # Map MELICA item-key -> MELICA cite-key (the only thing item.bibliography accepts).
    itemkey_to_citekey = {v: k for k, v in idx["citekey_to_itemkey"].items()}
    cited_citekeys = [itemkey_to_citekey.get(k) for k in cited_itemkeys]
    missing_ck = [(k, itemkey_to_citekey.get(k)) for k in cited_itemkeys if not itemkey_to_citekey.get(k)]
    if missing_ck:
        print(f"      WARN: {len(missing_ck)} item-keys lack a BBT cite-key:")
        for k, _ in missing_ck[:8]:
            t = idx["full"].get(k, {}).get("title", "?")
            print(f"        {k} | {t[:70]}")
    cited_citekeys = [c for c in cited_citekeys if c]

    # Render one cite-key at a time so each entry stays paired with its key.
    # (BBT's chicago-author-date sorts batch entries alphabetically by author, which
    # breaks key-order pairing in batched calls.)
    all_entries = []
    all_keys = []
    for i, ck in enumerate(cited_citekeys, 1):
        try:
            html = rpc(
                "item.bibliography",
                [[ck], {"id": "chicago-author-date", "contentType": "html"}, LIBRARY_ID],
                timeout=30,
            )
        except RuntimeError as e:
            print(f"      [{i}/{len(cited_citekeys)}] FAILED {ck}: {e}")
            continue
        ents = re.findall(r'<div class="csl-entry"[^>]*>.*?</div>', html, re.DOTALL)
        if not ents:
            print(f"      [{i}/{len(cited_citekeys)}] NO ENTRY for {ck}")
            continue
        if len(ents) > 1:
            print(f"      [{i}/{len(cited_citekeys)}] {ck} returned {len(ents)} entries; using first")
        all_entries.append(ents[0])
        all_keys.append(ck)
        if i % 10 == 0:
            print(f"      [{i}/{len(cited_citekeys)}] rendered so far")
    print(f"      flattened to {len(all_entries)} csl-entry divs from {len(all_keys)} keys")
    if len(all_entries) != len(all_keys):
        print(f"      WARN: entry count {len(all_entries)} != key count {len(all_keys)}")

    # Inject <i id="zotero|GROUP/KEY"></i> anchors into each entry. Match by order.
    paired = []
    for entry_html, ck in zip(all_entries, all_keys):
        ik = idx["citekey_to_itemkey"].get(ck)
        if ik:
            anchor = f'<i id="zotero|{GROUP_ID}/{ik}"></i>'
            entry_html = re.sub(
                r'(<div class="csl-entry"[^>]*>)',
                lambda m: m.group(1) + anchor,
                entry_html, count=1,
            )
        # Compute a sort key: rendered surname (lowercase, ascii-folded) for Chicago A-D order
        plain = re.sub(r"<[^>]+>", "", entry_html)
        plain = re.sub(r"^\s+", "", plain)
        sort_key = norm_title(plain[:60])
        paired.append((sort_key, entry_html))

    # Strip COinS spans for cleanliness (they leaked through inside csl-entry on some items)
    paired = [(k, re.sub(r'<span class="Z3988"[^>]*></span>\s*', "", e)) for k, e in paired]

    # Sort alphabetically by surname (Chicago A-D convention)
    paired.sort(key=lambda p: p[0])
    new_entries = [e for _, e in paired]
    new_bib_html = (
        '<!-- BIBLIOGRAPHY START -->\n'
        '<div class="csl-bib-body">\n  '
        + "\n  ".join(new_entries)
        + '\n</div>\n<!-- BIBLIOGRAPHY END -->\n'
    )
    nb["cells"][87]["source"] = [new_bib_html]
    print(f"      bibliography cell rewritten with {len(new_entries)} entries")

    # ---------------- WRITE PHASE ----------------
    print(f"\n[8/8] Writing notebook (backup -> {NB_BAK.name})...", flush=True)
    if not NB_BAK.exists():
        NB_BAK.write_bytes(NB.read_bytes())
        print(f"      backup written: {NB_BAK}")
    NB.write_text(json.dumps(nb, indent=1, ensure_ascii=False), encoding="utf-8")
    print(f"      notebook written: {NB}")
    print()
    print("=== DONE ===")


if __name__ == "__main__":
    main()
